// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIHmbx8Jt5cxtI3SOYzFSE5yYV_0TBgZM',
    appId: '1:279414273306:web:480576713109e061dca8a3',
    messagingSenderId: '279414273306',
    projectId: 'ohana-admin',
    authDomain: 'ohana-admin.firebaseapp.com',
    storageBucket: 'ohana-admin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmoHphyHBCZbmkRwKjf-Ckrw-61qc5_FE',
    appId: '1:279414273306:android:8ce48f0b8c2c73c3dca8a3',
    messagingSenderId: '279414273306',
    projectId: 'ohana-admin',
    storageBucket: 'ohana-admin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGHA1SIoclVDU84absI6XdbC8oPtWAcZU',
    appId: '1:279414273306:ios:67253eebe537b14bdca8a3',
    messagingSenderId: '279414273306',
    projectId: 'ohana-admin',
    storageBucket: 'ohana-admin.appspot.com',
    iosBundleId: 'com.example.ohanaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGHA1SIoclVDU84absI6XdbC8oPtWAcZU',
    appId: '1:279414273306:ios:67253eebe537b14bdca8a3',
    messagingSenderId: '279414273306',
    projectId: 'ohana-admin',
    storageBucket: 'ohana-admin.appspot.com',
    iosBundleId: 'com.example.ohanaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIHmbx8Jt5cxtI3SOYzFSE5yYV_0TBgZM',
    appId: '1:279414273306:web:ed7ff54b45427752dca8a3',
    messagingSenderId: '279414273306',
    projectId: 'ohana-admin',
    authDomain: 'ohana-admin.firebaseapp.com',
    storageBucket: 'ohana-admin.appspot.com',
  );
}
